# Generated by Django 2.2.6 on 2019-10-30 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_game_gameplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.League'),
            preserve_default=False,
        ),
    ]
