# Generated by Django 2.2.6 on 2019-10-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='winnings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='rebuys',
            field=models.IntegerField(default=0),
        ),
    ]
