# Generated by Django 2.2.6 on 2019-10-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191029_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.TextField(default='Missing'),
            preserve_default=False,
        ),
    ]
