# Generated by Django 2.2.6 on 2019-11-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_eventplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('P', 'Proposed'), ('C', 'Confirmed'), ('X', 'Cancelled'), ('F', 'Finished')], default='C', max_length=2),
            preserve_default=False,
        ),
    ]
