# Generated by Django 2.2.6 on 2019-11-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_players',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='event',
            name='min_players',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='eventplayer',
            name='attendance',
            field=models.CharField(choices=[('NA', 'No response'), ('NI', 'Not interested'), ('IN', 'Interested'), ('AT', 'Attending'), ('AD', 'Attended'), ('NS', 'No show'), ('CX', 'Cancelled')], max_length=2),
        ),
    ]
