# Generated by Django 2.2.6 on 2019-11-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191114_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
