# Generated by Django 2.2.6 on 2019-11-23 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_eventchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='high_hand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='high_hand_stake',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='high_hand_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='high_hand_wins', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='eventplayer',
            name='high_hand_stake',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventplayer',
            name='high_hand_winnings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
