# Generated by Django 2.2.6 on 2019-11-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191123_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventplayer',
            name='high_hand_stake',
            field=models.BooleanField(default=False),
        ),
    ]
